services:
  postgres-order-service:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER_FOR_ORDER_SERVICE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_FOR_ORDER_SERVICE}
      POSTGRES_DB: ${POSTGRES_DB_FOR_ORDER_SERVICE}
    ports:
      - "${POSTGRES_PORT_FOR_ORDER}:5432"
    volumes:
      - pgdata_order:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_FOR_ORDER_SERVICE} -d ${POSTGRES_DB_FOR_ORDER_SERVICE}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  postgres-user-service:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER_FOR_USER_SERVICE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_FOR_USER_SERVICE}
      POSTGRES_DB: ${POSTGRES_DB_FOR_USER_SERVICE}
    ports:
      - "${POSTGRES_PORT_FOR_USER}:5432"
    volumes:
      - pgdata_user:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_FOR_USER_SERVICE} -d ${POSTGRES_DB_FOR_USER_SERVICE}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  postgres-auth-service:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER_FOR_AUTH_SERVICE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_FOR_AUTH_SERVICE}
      POSTGRES_DB: ${POSTGRES_DB_FOR_AUTH_SERVICE}
    ports:
      - "${POSTGRES_PORT_FOR_AUTH}:5432"
    volumes:
      - pgdata_auth:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER_FOR_AUTH_SERVICE} -d ${POSTGRES_DB_FOR_AUTH_SERVICE}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped


volumes:
  pgdata_order:
  pgdata_user:
  pgdata_auth: